### ISSUE TITLE
Shiny assessment feedback

### ISSUE THREAD

**Issue by jonekeat** [Kiannn1124/Intern_Shiny#1]
Hi Wei Kian, thanks for attempting the shiny assessment, please find my feedbacks below:

1. The interface fully fulfilled all requirements, user is able to input some data, calculate and visualize result all in the app, well done!

2. The UI design is kind of weird, where the tabset panel is at top right corner, but the output is at bottom. This makes user look at 2 different places to switch for outputs, and is not user-friendly
![image](https://user-images.githubusercontent.com/51594799/231631390-9732d4a5-5ff8-41f3-8805-55e2b8e41b11.png)

3. For fileInput component, the input file format must be specify wherever possible, else user can upload any files (zip, xlsx, .R, ...), and you apps will run into issue
https://github.com/Kiannn1124/Intern_Shiny/blob/c41f3d7b0e8e81178399791caff71d569101c9a3/app.R#L7

4. Since the output number are currency values, we can format it using accounting format (put thousand separator), especially y-axis of graph & table cells. And legend of the graph (Loss Year) should not be continuous, should convert to integer instead
![image](https://user-images.githubusercontent.com/51594799/231633048-f88844f9-ef01-4656-8a89-eff9a47e21c3.png)
![image](https://user-images.githubusercontent.com/51594799/231633287-ca90dc8c-fbb7-4250-8d8c-f4b9ca5e12a6.png)

5. The table formatting is quite good, but we should enhance the table cell formatting, like putting different cell/background color to differentiate which cell is input values and which is projected.

6. The app is only able to handle 3 accident year perfectly, but if user upload data for less than 3 accident year or more than 3 accident year, then app will have error or only display first 4 years. Instead user will expect the app to be more dynamic to handle dynamic number of rows
![image](https://user-images.githubusercontent.com/51594799/231635140-97ad6295-0d13-4f0d-9894-af4729b30932.png)
![image](https://user-images.githubusercontent.com/51594799/231635237-0765fc26-25db-46a1-ba86-e0ca09acec50.png)

**Comment by Kiannn1124** [comment]
All good ^.^
